### ISSUE TITLE
Error creating initial 'myproj' project

### ISSUE THREAD

**Issue by jcwren** [apache/mynewt-core#2507]
Following the instructions for creating a first project, and get this error when running `newt upgrade`

Note that I did not change the `vers` field in the `project.yml` file. The instructions [here](http://mynewt.apache.org/latest/get_started/project_create.html#fetching-the-mynewt-source-repository-and-dependencies) don't match up with what's in the file.

```
jcw@debresc:~/Projects/myproj$ newt version
Apache Newt
   Version: 1.7.0
  Git Hash: unknown
Build Date: 2019-09-03_13:44

jcw@debresc:~/Projects$ newt new myproj
Downloading project skeleton from apache/mynewt-blinky...
Downloading repository mynewt-blinky (commit: mynewt_1_7_0_tag) from https://github.com/apache/mynewt-blinky.git
Installing skeleton in myproj...
Project myproj successfully created.
```
```
jcw@debresc:~/Projects$ cd myproj/
jcw@debresc:~/Projects/myproj$ cat project.yml
#
# [snip comments for brevity]
#

project.name: "my_project"

project.repositories:
    - apache-mynewt-core

# Use github's distribution mechanism for core ASF libraries.
# This provides mirroring automatically for us.
#
repository.apache-mynewt-core:
    type: github
    vers: 1.7.0
    user: apache
    repo: mynewt-core
```
```
jcw@debresc:~/Projects/myproj$ newt upgrade
Downloading repository mynewt-core (commit: master) from https://github.com/apache/mynewt-core.git
Downloading repository mynewt-nimble (commit: master) from https://github.com/apache/mynewt-nimble.git
Downloading repository mcuboot (commit: master) from https://github.com/JuulLabs-OSS/mcuboot.git
Downloading repository mynewt-mcumgr (commit: master) from https://github.com/apache/mynewt-mcumgr.git
Making the following changes to the project:
    install apache-mynewt-core (1.7.0)
    install apache-mynewt-nimble (1.2.0)
    install mcuboot (1.3.1)
apache-mynewt-core successfully upgraded to version 1.7.0
apache-mynewt-nimble successfully upgraded to version 1.2.0
Error: Error updating "mcuboot": error: The following untracked working tree files would be overwritten by checkout:
        ext/mbedtls/include/mbedtls/check_config.h
        ext/mbedtls/include/mbedtls/config.h
Please move or remove them before you switch branches.
Aborting

jcw@debresc:~/Projects/myproj$
```
