### ISSUE TITLE
Building for nRF52810

### ISSUE THREAD

**Issue by danielkucera** [apache/mynewt-core#2691]
Hi,

I'm trying to compile for nRF52810 but failing. I cannot find any example so I am trying to bend 52832 example.
I have found this patch from @alvarop : https://github.com/alvarop/mynewt-core/commit/9fe0f2b96322a48824418bc005db42f1c52d0a22#diff-5f33e3c2dbee3aecfa37c7f194a190d72331e43ecddc3f2a6d7fac768408e997
But I am getting hardfault.

This is part of my syscfg.yml:
```
syscfg.defs:
    BSP_NRF52:
        description: 'Set to indicate that BSP has NRF52'
        value: 1
    ENC_FLASH_DEV:
        description: 'Encrypting flash driver over interal flash for testing'
        value: 0
    RAM_RESIDENT:
        description: 'Compile app to be loaded to RAM'
        value: 0

syscfg.vals:
    # Enable nRF52832 MCU
    MCU_TARGET: nRF52810

    UART_0_PIN_TX: 14
    UART_0_PIN_RX: 15
    UART_0: 1
...
```
When debugging, I can see that here https://github.com/apache/mynewt-core/blob/master/hw/mcu/nordic/nrf52xxx/src/system_nrf52.c the code for NRF52 is executed instead of NRF52810_XXAA.
How do I undefine `NRF52` and define `NRF52810_XXAA` ?
