### ISSUE TITLE
RAM overflow error when build app for PineTime

### ISSUE THREAD

**Issue by Kisszalimo** [apache/mynewt-core#3066]
Hi,
I would like to try out a [simple demo app](https://github.com/apache/mynewt-core/pull/2951/commits/0ad5f0ed5d452dafca8c56ed45f2682ebc94c602) using LVGL which was introduced in Mynewt v1.11. Unfortunately I get an error while building project:

```
$ newt build limon_v1
...
Error: /usr/lib/gcc/arm-none-eabi/10.3.1/../../../arm-none-eabi/bin/ld: /home/(...)/apache-mynewt-newt-bin-linux-1.11.0/limon_v1/bin/targets/limon_v1/app/apps/blinky/blinky.elf section `.bss' will not fit in region `RAM'
/usr/lib/gcc/arm-none-eabi/10.3.1/../../../arm-none-eabi/bin/ld: region RAM overflowed with stack
/usr/lib/gcc/arm-none-eabi/10.3.1/../../../arm-none-eabi/bin/ld: region `RAM' overflowed by 5156 bytes
collect2: error: ld returned 1 exit status
```

If I remember correctly, I only added ```@apache-mynewt-core/hw/drivers/display/lvgl``` into app ```pkg.yml``` as a package dependency and set LVGL display resolution and ```LCD_DC_PIN``` in the appropriate ```syscfg.yml``` file. I did not modify any further files and I use built-in LVGL demos.

**Comment by kasjer** [comment]
@Kisszalimo, while I don't have pinetime watch to verify that it works, here is what you may try:

There is pending PR #3063 that adds options that can tweak LVGL a little bit so it will fit in memory.
You could merge commits from this PR to your mynewt-core branch.
I hope PR will be merged soon.

Next you can change you target syscfg.yml to have this:
```yml
syscfg.vals:
    LCD_ITF: spi
    LCD_SPI_DEV_NAME: '"spi0"'
    LCD_SPI_FREQ: 8000
    LCD_SPI_MODE: BUS_SPI_MODE_0
    LCD_CS_PIN: 25
    LCD_RESET_PIN: 26
    LCD_DC_PIN: 18
    LCD_BL_PIN: 13
    LVGL_DISPLAY_HORIZONTAL_RESOLUTION: 240
    LVGL_DISPLAY_VERTICAL_RESOLUTION: 240
    LVGL_ST7789: 1
   # this reduce memory usage of LVGL
    LV_MEM_SIZE: 40000
```
I did test it on **nordic_pca10040** target that has same MCU but no other peripherals except LCD
